name: Development build

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Build

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}

    steps:
      - name: Clone project
        uses: actions/checkout@v4

      - name: Install and run Luacheck
        uses: nebularg/actions-luacheck@v1
        with:
          args: "--no-color -q"
          annotate: warning
          
      - name: Update Curseforge Translations
        run: ./cf_localizations.sh
        #env:
        #  CF_API_KEY: ${{ secrets.CF_API_KEY }}

      - name: Package and release
        uses: BigWigsMods/packager@master
        with:
          args: -d -z
