name: CI

on:
  push:
    branches:
      - locales

jobs:
  build:
    runs-on: [self-hosed, macos-11]

    steps:
    - uses: actions/checkout@v1

    - name: Install and run Luacheck
      uses: nebularg/actions-luacheck@v1
      with:
        args: "--no-color -q"

    - name: Update Curseforge Translations
      run: ./cf_translations.sh
      env:
        CF_API_KEY: ${{ secrets.CF_API_KEY }}
