name: Package and Build

on:
  push:
    tags:
      - '**'

jobs:
  build:
    runs-on: self-hosted

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      #WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      #WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Clone project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      #- name: Install and run Luacheck
      #  uses: nebularg/actions-luacheck@v1
      #  with:
      #    args: "--no-color -q"

      - name: Update Curseforge Translations
        #workaround until figure out why it can't find file
        run: /Users/hector/Desktop/AtlasLootClassic_Cata/cf_translations.sh

      - name: Package and release
        uses: BigWigsMods/packager@v2
        with:
          args: -g cata -w 0
